#!/bin/bash

#判断参数个数
if [ $# -lt 1 ]
then
	echo Not Enough Arguement!
fi

for host in centos1 centos2 centos3
do 
	echo =========== $host ==============
		
	#遍历所有文件，挨个发送
	for file in $@
	do 
		#判断文件是否存在
		if [ -e $file ]
			then
				#获取父目录。-P找到软连接的源文件目录，dirname $file 获取当前文件的目录
				pdir=$(cd -P $(dirname $file); pwd)
				

				#获取当前文件名称
				fname=$(basename $file)
					
				#-p 不管文件是否存在都能够创建成功,不会影响已有文件夹下的文件
				ssh $host "mkdir -p $pdir"
				rsync -av $pdir/$fname $host:$pdir
			else
				echo $file does not exist!
		fi
	done
done			
